---
title: "Process data for meta analyses of the IRAP's reliability"
author: "Ian Hussey"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE)
```

```{r}

# set seed for computational reproducibility
set.seed(42)

# dependencies
library(tidyverse)
library(metafor)
library(knitr)
library(kableExtra)
library(psych)
library(qgraph)


# function to round all numeric vars in a data frame
round_df <- function(df, n_digits = 3) {
  df %>% mutate_if(is.numeric, round, digits = n_digits)
}

probability_of_superiority_function <- function(x, y) {
  nx <- length(x)
  ny <- length(y)
  rx <- sum(rank(c(x, y))[1:nx])
  A = (rx / nx - (nx + 1) / 2) / ny
  return(A)
}

spearman_brown_correction <- function(r_pearson) {
  inversion <- ifelse(r_pearson < 0, -1, 1)
  val <- round(2*abs(r_pearson)/(1 + abs(r_pearson)), 2)
  return(val*inversion)
}

apa_p_value <- function(p){
  p_formatted <- ifelse(p >= 0.001, paste("=", round(p, 3)),
                        ifelse(p < 0.001, "< .001", NA))
  p_formatted <- gsub(pattern = "0.", replacement = ".", x = p_formatted, fixed = TRUE)
  p_formatted
}

add_heterogeneity_metrics_to_forest <- function(fit) {
  ## more detailed
  # bquote(paste("RE Model (Q(df = ", .(formatC(fit$k - 1)), ") = ", 
  #              .(formatC(round(fit$QE, 2))), 
  #              ", p ", .(formatC(apa_p_value(fit$QEp))),
  #              ", ", tau^2, " = ", .(formatC(round(fit$tau2, 1))), 
  #              ", ", I^2, " = ", .(formatC(round(fit$I2, 1))),
  #              "%, ", H^2," = ", .(formatC(round(fit$H2, 1))), ")"))
  ## less detailed
  bquote(paste("RE Model (", tau^2, " = ", .(formatC(round(fit$tau2, 1))), 
               ", ", I^2, " = ", .(formatC(round(fit$I2, 1))),
               "%, ", H^2," = ", .(formatC(round(fit$H2, 1))), ")"))
}

# table format in output
options(knitr.table.format = "html") 

# create directory needed to save output
dir.create("permutations")

```

# Data 

and exclusion of outliers on the basis of median mean_rt +/- 2MAD

```{r}

data_cleaned <- read.csv("../trial level data/data_internalconsistency_cleaned_trial_level.csv") %>%
  filter(str_detect(domain, "Personality")) %>%
  mutate(domain = str_remove(domain, "Personality - "))

temp <- data_cleaned %>%
  distinct(unique_id, .keep_all = TRUE) %>%
  select(unique_id, mean_rt) %>%
  mutate(median_mean_rt = median(mean_rt, na.rm = TRUE),
         mad_mean_rt = mad(mean_rt, na.rm = TRUE)) %>%
  round_df(0) %>%
  # exclude median +- 2MAD
  mutate(rt_outlier = ifelse(mean_rt < median_mean_rt-mad_mean_rt*2 |
                            mean_rt > median_mean_rt+mad_mean_rt*2, TRUE, FALSE)) %>%
  filter(rt_outlier == FALSE) %>%
  select(unique_id, rt_outlier)

data_cleaned_outliers <- data_cleaned %>%
  full_join(temp, by = "unique_id") %>%
  mutate(rt_outlier = ifelse(is.na(rt_outlier), TRUE, rt_outlier))

data_cleaned_outliers_removed <- data_cleaned_outliers %>%
  filter(rt_outlier == FALSE)

```

# D scores

```{r}

data_D_scores <- 
  full_join(
    data_cleaned_outliers_removed %>%
      filter(rt <= 10000) %>%
      group_by(unique_id) %>%
      summarize(mean_con = mean(rt[block_type == "con"], na.rm = TRUE),
                mean_incon = mean(rt[block_type == "incon"], na.rm = TRUE),
                sd = mean(rt, na.rm = TRUE)) %>%
      ungroup() %>%
      mutate(D = (mean_incon - mean_con)/sd) %>%
      select(unique_id, D_overall = D),
    data_cleaned_outliers_removed %>%
      filter(rt <= 10000) %>%
      group_by(unique_id, trial_type) %>%
      summarize(mean_con = mean(rt[block_type == "con"], na.rm = TRUE),
                mean_incon = mean(rt[block_type == "incon"], na.rm = TRUE),
                sd = mean(rt, na.rm = TRUE)) %>%
      ungroup() %>%
      mutate(D = (mean_incon - mean_con)/sd) %>%
      select(unique_id, trial_type, D) %>%
      spread(trial_type, D) %>%
      left_join(select(distinct(data_cleaned_outliers_removed, unique_id, .keep_all = TRUE), unique_id, domain), by = "unique_id") %>%
      rename(D_tt1 = tt1, 
             D_tt2 = tt2, 
             D_tt3 = tt3, 
             D_tt4 = tt4),
    by = "unique_id"
  ) %>%
  separate(unique_id, into = c("domain", "id"), sep = "_") %>%
  mutate(D_overall = ifelse(domain == "neuroticism", D_overall*-1, D_overall),
         # reverse score trial types for neuroticism
         D_tt1 = ifelse(domain == "neuroticism", D_tt1*-1, D_tt1),
         D_tt2 = ifelse(domain == "neuroticism", D_tt2*-1, D_tt2),
         D_tt3 = ifelse(domain == "neuroticism", D_tt3*-1, D_tt3),
         D_tt4 = ifelse(domain == "neuroticism", D_tt4*-1, D_tt4)) %>%
  pivot_wider(names_from = "domain",
              values_from = c("D_overall", "D_tt1", "D_tt2", "D_tt3", "D_tt4"))
  # # reorder trial types for neuroticism
  # rename(temp_1 = D_tt1_neuroticism,
  #        temp_2 = D_tt2_neuroticism,
  #        temp_3 = D_tt3_neuroticism,
  #        temp_4 = D_tt4_neuroticism) %>%
  # rename(D_tt1_neuroticism = temp_3,
  #        D_tt2_neuroticism = temp_4,
  #        D_tt3_neuroticism = temp_1,
  #        D_tt4_neuroticism = temp_2)

```

# Cors

```{r fig.height=5, fig.width=5}

cors <- data_D_scores %>%
  select(starts_with("D_overall")) %>%
  rename_all(funs(str_remove(., pattern = "D_overall_"))) %>%
  cor(use = "pairwise.complete.obs", method = "pearson") %>%
  round(2)

cors

qgraph(cors, negDashed = TRUE)

```

```{r fig.height=5, fig.width=5}

cors <- data_D_scores %>%
  select(starts_with("D_tt1")) %>%
  rename_all(funs(str_remove(., pattern = "D_tt1_"))) %>%
  cor(use = "pairwise.complete.obs", method = "pearson") %>%
  round(2)

cors

qgraph(cors, negDashed = TRUE)

```

```{r fig.height=5, fig.width=5}

cors <- data_D_scores %>%
  select(starts_with("D_tt2")) %>%
  rename_all(funs(str_remove(., pattern = "D_tt2_"))) %>%
  cor(use = "pairwise.complete.obs", method = "pearson") %>%
  round(2)

cors

qgraph(cors, negDashed = TRUE)

```

```{r fig.height=5, fig.width=5}

cors <- data_D_scores %>%
  select(starts_with("D_tt3")) %>%
  rename_all(funs(str_remove(., pattern = "D_tt3_"))) %>%
  cor(use = "pairwise.complete.obs", method = "pearson") %>%
  round(2)

cors

qgraph(cors, negDashed = TRUE)

```

```{r fig.height=5, fig.width=5}

cors <- data_D_scores %>%
  select(starts_with("D_tt4")) %>%
  rename_all(funs(str_remove(., pattern = "D_tt4_"))) %>%
  cor(use = "pairwise.complete.obs", method = "pearson") %>%
  round(2)

cors

qgraph(cors, negDashed = TRUE)

```


```{r}

library(qgraph)
library(bootnet)

network <-
  estimateNetwork(data_D_scores %>%
                    select(starts_with("D_overall")) %>%
                    rename_all(funs(str_remove(., pattern = "D_overall_"))),
                  default   = "EBICglasso",
                  corMethod = "spearman",
                  missing   = "pairwise",
                  verbose   = FALSE,
                  threshold = TRUE)

plot(network)

```

```{r fig.height=5, fig.width=5}

# cors <- data_D_scores %>%
#   select(starts_with("D_tt")) %>%
#   rename_all(funs(str_remove_all(., pattern = "D_tt"))) %>%
#   rename_all(funs(str_remove_all(., pattern = "_"))) %>%
#   cor(use = "pairwise.complete.obs", method = "pearson") %>%
#   round(2)
# 
# cors
# 
# qgraph(cors)

```

